# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4304d415084bb2601ac73419cce062f7e3417c6baec7131b6ba10b5df9fe4b9a619355b830e7cf52b1990907fde4a7ea4b88868d080e6fa680469898dab908e7

test:
  secret_key_base: d951be1b407c940a37b8ca8cbcd5b4536da2fa014334a0efd8d64f962a93547a866bb9011eb0157a5f6e805d4c5bed1b87ce749bedac920e2a33cc25e9a967cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
